name: date_format
description: A simple API to format dates.
version: 1.0.4
homepage: https://github.com/tejainece/date_format
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0
